name = "CompilerCaching"
uuid = "9db33cc3-5358-4881-8759-fa4194144afd"
version = "0.1.0"

[deps]
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Scratch = "1"
julia = "1.11"
